version: "3"

services:
  vanblog:
    # 默认 dockerhub 源
    image: mereith/van-blog:latest
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      # 图片资源允许的域名，英文逗号分隔。作者 logo 加载不出来请检查此项。
      VAN_BLOG_ALLOW_DOMAINS: "www.mereith.com"
      # CDN URL，包含协议，部署到 cdn 的时候用。在开启 cdn 之前请不要设置此项。
      # VAN_BLOG_CDN_URL: "https://www.mereith.com"
      # mongodb 的地址
      VAN_BLOG_DATABASE_URL: "mongodb://vanBlog:vanBlog@mongo:27017/vanBlog?authSource=admin"
      # jwt 密钥，随机字符串即可。请注意保密！所有的密码都由此密钥签发！
      VAN_BLOG_JWT_SECRET: "zxcvbnm[]123"
      # 邮箱地址，用于自动申请 https 证书
      EMAIL: "fuxinyujerry@gmail.com"
      # 内嵌评论系统的 db 名，默认为 waline
      VAN_BLOG_WALINE_DB: "waline"
    volumes:
      # 图床文件的存放地址，按需修改。
      - ${PWD}/data/static:/app/static
      # 日志文件
      - ${PWD}/log:/var/log
      # caddy 配置存储
      - ${PWD}/caddy/config:/root/.config/caddy
      # caddy 证书存储
      - ${PWD}/caddy/data:/root/.local/share/caddy
    ports:
      - 80:80
      - 443:443
  mongo:
    image: mongo
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      # 如果你改了这两个，那上面的数据库连接地址也要同步修改。
      # mongoDB 初始化用户名
      MONGO_INITDB_ROOT_USERNAME: vanBlog
      # mongoDB 初始化密码
      MONGO_INITDB_ROOT_PASSWORD: vanBlog
    volumes:
      # mongoDB 数据存放地址，按需修改。
      - ${PWD}/data/mongo:/data/db
